using Microsoft.EntityFrameworkCore;
using XtremeType.Data;
using XtremeType.Services.Implementations;
using XtremeType.Services.Interfaces;
using Microsoft.AspNetCore.Authentication.Cookies;
using XtremeType.Services;
using Microsoft.AspNetCore.Mvc.Routing;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllersWithViews();
builder.Services.AddSingleton<IUrlHelperFactory, UrlHelperFactory>();
builder.Services.AddDbContext<AppDbContext>(options => options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));
builder.Services.AddHttpClient();
builder.Services.AddScoped<IEmailService, EmailService>();
builder.Services.AddScoped<IDashboardService, DashboardService>();
builder.Services.AddScoped<IAccountService, AccountService>();
builder.Services.AddScoped<IAuditService, AuditService>();
builder.Services.AddScoped<IFrontendService, FrontendService>();
//builder.Services.AddScoped<StripePaymentService>();
//builder.Services.AddScoped<PayPalPaymentService>();
//builder.Services.AddScoped<PaymentManager>();
//builder.Services.AddScoped<IPaymentService>(sp => sp.GetRequiredService<PaymentManager>());
builder.Services.AddSession();
builder.Services.AddHttpContextAccessor();
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie(options => { options.LoginPath = "/Account"; options.LogoutPath = "/Account/Logout";});
var app = builder.Build();
if (!app.Environment.IsDevelopment()) { app.UseExceptionHandler("/Home/Error"); app.UseHsts();}
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseSession(); 
app.UseAuthentication();
app.UseAuthorization();
app.MapControllerRoute( name: "login-shortcut", pattern: "login",defaults: new { area = "Admin", controller = "Account", action = "Login" });
app.MapControllerRoute( name: "forgot-password-shortcut", pattern: "forgot-password", defaults: new { area = "Admin", controller = "Account", action = "ForgotPassword" });
app.MapControllerRoute( name: "dashboard-shortcut", pattern: "dashboard", defaults: new { area = "Admin", controller = "Dashboard", action = "Index" });
app.MapControllerRoute( name: "areas", pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
app.MapControllerRoute( name: "default", pattern: "{controller=Home}/{action=Index}/{id?}");
app.Run();
